### ISSUE TITLE
Application communication protocol design

### ISSUE THREAD

**Issue by supunTE** [the-ai-team/razor#15]
Epic:

### Description
Design and create documentation of front-end and back-end communication protocol.

### Tasks

- [x] Study communication protocol and sockets
- [x] Authentication tech solution
- [x] Event communication protocol documentation
