### ISSUE TITLE
Schema validation 

### ISSUE THREAD

**Issue by supunTE** [the-ai-team/razor#17]
Epic:

### Tasks

- [x] Refactor socket data models
- [x] Research about schema validation
- [x] Scheme validation for the backend
