### ISSUE TITLE
Generate code coverage

### ISSUE THREAD

**Issue by supunTE** [the-ai-team/razor#18]
Epic:

### Description
Generate code coverage and display badges

### Tasks

- [x] Generate code coverage
- [x] Make badges to display on read me
- [x] Display code coverage on PR
