### ISSUE TITLE
Planning file structure

### ISSUE THREAD

**Issue by supunTE** [the-ai-team/razor#21]
Epic:

### Tasks

- [x] Research on monorepo file structure
- [x] Plan file structure for the backend
- [x] Plan file structure for the frontend

**Comment by supunTE** [comment]
backend file structure 
https://docs.google.com/document/d/1_8mR0fWkkb-p5UAJUojaNT6hYKVIjQ_8ZJ3LEqOHEVI/edit?usp=sharing

**Comment by supunTE** [comment]
File structure updated for frontend.

**Comment by vidurathegeek** [comment]
@pasinducw review and update the doc.
