### ISSUE TITLE
Frontend Design

### ISSUE THREAD

**Issue by supunTE** [the-ai-team/razor#23]
Epic:

### Tasks

- [x] Plan UI wireframe design
- [x] Choose frontend component libraries
- [x] Design UI (Figma)

**Comment by supunTE** [comment]
Wireframe design
https://www.figma.com/proto/HuRfRnZbdW3rvOytxU0bvN/Razor---wireframe?node-id=3488%3A6008&scaling=min-zoom&page-id=247%3A43
![Razor - Web Client](https://user-images.githubusercontent.com/33794760/209351180-08ed5dc0-a239-42ab-badb-b30b0e9d35ab.png)

**Comment by supunTE** [comment]
UI design prototype - https://www.figma.com/proto/ApyAvJNhI1TPbCJZIHTqZQ/Web-client-design?node-id=3%3A3&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A3

![Home](https://user-images.githubusercontent.com/33794760/210195332-afb70f01-8d4b-4029-9809-829f987f565b.png)
![Lobby](https://user-images.githubusercontent.com/33794760/210195348-b80ee316-44b9-41f2-8e7b-33c26dbc57c2.png)
![Race](https://user-images.githubusercontent.com/33794760/210195353-232bc0e0-182d-4101-baac-b6c084cafe58.png)
![Leaderboard](https://user-images.githubusercontent.com/33794760/210195342-e415ae86-fcd5-4441-9f82-d1e7599e1de4.png)
